services:
  connector-feed-aggregator:
    image: connector-feed-aggregator:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${FEED_AGGREGATOR_TOKEN}
      - CONNECTOR_ID=${FEED_AGGREGATOR_ID}
      - CONNECTOR_NAME=Feed Aggregator
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_SCOPE=report
      - FEED_URLS=${FEED_URLS} # To be stored as a iist of tuples of (Name, URL) -> (String,String) format
      - FEED_KEYWORDS=${FEED_KEYWORDS} # To be stored as a list of strings
    restart: always
    networks:
      - docker_default

networks:
    docker_default:
      external: true